version: "3"
services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app:ro
      - /app/node_modules
    environment:
      - PORT=3000
      - NODE_ENV=development
    command: npm run dev
    deploy:
      replicas: 1
  #   depend_on:
  #     - mongo
  # mongo:
  #   image: mongo
  #   environment:
  #     - MONGO_INIT_ROOT_USERNAME=mohsin
  #     - MONSO_INITDB_ROOT_PASSWORD=password
  #   volumes:
  #     - mongo-db:/data/db
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./src/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
# volumes:
#   mongo-db